/* Service worker for a published talk deck.
 *
 * Cache-first over an explicit, build-time asset list. Not a runtime-populated
 * cache: a deck is a fixed set of files known at build time, and precaching all
 * of them is what makes the deck work in a room with no network — which is the
 * only reason this file exists.
 *
 * CACHE_NAME embeds a content hash of the asset list, so a republish creates a
 * new cache and the activate handler drops every older one. Without that, a
 * viewer who installed an earlier version would keep serving it forever.
 *
 * Generated by .github/scripts/talk-build-html.py — do not edit dist/sw.js.
 */

const CACHE_NAME = 'talk-2026-08-18-building-ai-systems-at-artin-094322880c18';
const PRECACHE = [
  "./",
  "2026-08-18-building-ai-systems-at-artin-handout.pdf",
  "2026-08-18-building-ai-systems-at-artin-slides.pdf",
  "2026-08-18-building-ai-systems-at-artin-speaker-notes.pdf",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "katex/fonts/KaTeX_AMS-Regular.ttf",
  "katex/fonts/KaTeX_AMS-Regular.woff",
  "katex/fonts/KaTeX_AMS-Regular.woff2",
  "katex/fonts/KaTeX_Caligraphic-Bold.ttf",
  "katex/fonts/KaTeX_Caligraphic-Bold.woff",
  "katex/fonts/KaTeX_Caligraphic-Bold.woff2",
  "katex/fonts/KaTeX_Caligraphic-Regular.ttf",
  "katex/fonts/KaTeX_Caligraphic-Regular.woff",
  "katex/fonts/KaTeX_Caligraphic-Regular.woff2",
  "katex/fonts/KaTeX_Fraktur-Bold.ttf",
  "katex/fonts/KaTeX_Fraktur-Bold.woff",
  "katex/fonts/KaTeX_Fraktur-Bold.woff2",
  "katex/fonts/KaTeX_Fraktur-Regular.ttf",
  "katex/fonts/KaTeX_Fraktur-Regular.woff",
  "katex/fonts/KaTeX_Fraktur-Regular.woff2",
  "katex/fonts/KaTeX_Main-Bold.ttf",
  "katex/fonts/KaTeX_Main-Bold.woff",
  "katex/fonts/KaTeX_Main-Bold.woff2",
  "katex/fonts/KaTeX_Main-BoldItalic.ttf",
  "katex/fonts/KaTeX_Main-BoldItalic.woff",
  "katex/fonts/KaTeX_Main-BoldItalic.woff2",
  "katex/fonts/KaTeX_Main-Italic.ttf",
  "katex/fonts/KaTeX_Main-Italic.woff",
  "katex/fonts/KaTeX_Main-Italic.woff2",
  "katex/fonts/KaTeX_Main-Regular.ttf",
  "katex/fonts/KaTeX_Main-Regular.woff",
  "katex/fonts/KaTeX_Main-Regular.woff2",
  "katex/fonts/KaTeX_Math-BoldItalic.ttf",
  "katex/fonts/KaTeX_Math-BoldItalic.woff",
  "katex/fonts/KaTeX_Math-BoldItalic.woff2",
  "katex/fonts/KaTeX_Math-Italic.ttf",
  "katex/fonts/KaTeX_Math-Italic.woff",
  "katex/fonts/KaTeX_Math-Italic.woff2",
  "katex/fonts/KaTeX_SansSerif-Bold.ttf",
  "katex/fonts/KaTeX_SansSerif-Bold.woff",
  "katex/fonts/KaTeX_SansSerif-Bold.woff2",
  "katex/fonts/KaTeX_SansSerif-Italic.ttf",
  "katex/fonts/KaTeX_SansSerif-Italic.woff",
  "katex/fonts/KaTeX_SansSerif-Italic.woff2",
  "katex/fonts/KaTeX_SansSerif-Regular.ttf",
  "katex/fonts/KaTeX_SansSerif-Regular.woff",
  "katex/fonts/KaTeX_SansSerif-Regular.woff2",
  "katex/fonts/KaTeX_Script-Regular.ttf",
  "katex/fonts/KaTeX_Script-Regular.woff",
  "katex/fonts/KaTeX_Script-Regular.woff2",
  "katex/fonts/KaTeX_Size1-Regular.ttf",
  "katex/fonts/KaTeX_Size1-Regular.woff",
  "katex/fonts/KaTeX_Size1-Regular.woff2",
  "katex/fonts/KaTeX_Size2-Regular.ttf",
  "katex/fonts/KaTeX_Size2-Regular.woff",
  "katex/fonts/KaTeX_Size2-Regular.woff2",
  "katex/fonts/KaTeX_Size3-Regular.ttf",
  "katex/fonts/KaTeX_Size3-Regular.woff",
  "katex/fonts/KaTeX_Size3-Regular.woff2",
  "katex/fonts/KaTeX_Size4-Regular.ttf",
  "katex/fonts/KaTeX_Size4-Regular.woff",
  "katex/fonts/KaTeX_Size4-Regular.woff2",
  "katex/fonts/KaTeX_Typewriter-Regular.ttf",
  "katex/fonts/KaTeX_Typewriter-Regular.woff",
  "katex/fonts/KaTeX_Typewriter-Regular.woff2",
  "katex/katex.min.css",
  "reveal/plugin/highlight/monokai.css",
  "reveal/plugin/highlight.js",
  "reveal/plugin/markdown.js",
  "reveal/plugin/notes.js",
  "reveal/plugin/search.js",
  "reveal/reset.css",
  "reveal/reveal.css",
  "reveal/reveal.js",
  "theme.css"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // NAVIGATIONS ARE NETWORK-FIRST. Everything else is cache-first.
  //
  // Cache-first on the document is how a viewer ends up presenting a deck that
  // was superseded hours ago: the worker answers from cache before the network
  // is ever consulted, so a republish is invisible until the worker itself
  // updates. That is belt to CACHE_NAME's braces — the cache key is now
  // content-addressed, so a republish DOES roll it, but a cache key is only
  // load-bearing while it is correct, and it was wrong for weeks without
  // anything noticing.
  //
  // The offline guarantee is untouched: the network attempt falls back to the
  // cached copy, so a room with no wifi still gets the deck. The cost is one
  // conditional request per navigation when online, which is nothing next to
  // standing in front of an audience presenting the wrong version.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => caches.match(request, { ignoreSearch: true })
          .then((hit) => hit || caches.match('index.html')))
    );
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(request).catch(() => Response.error());
    })
  );
});
